# ═══════════════════════════════════════════════════════════════
# CRIF - CRYPTO RESEARCH INTERACTIVE FRAMEWORK - WORKFLOW DEFINITION
# ═══════════════════════════════════════════════════════════════

# --- IDENTITY ---
id: product-analysis
type: implication
name: Product/Protocol Analysis
description: Comprehensive product evaluation covering protocol mechanics, value proposition, problem-solution fit, PMF signals, and red flags

# --- DEPENDENCIES ---
dependencies:
  objectives: "./framework/workflows/product-analysis/objectives.md"
  template: "./framework/workflows/product-analysis/template.md"
  guides:
    scope-clarification: "./framework/guides/scope-clarification.md"
    research-methodology: "./framework/guides/research-methodology.md"
    collaborative-research: "./framework/guides/collaborative-research.md"
    output-standards: "./framework/guides/output-standards.md"

# --- CONFIGURATION ---
configuration:
  research_depth: standard
  output_type: comprehensive
  output_format: markdown
  output_path: "./workspaces/{workspace_id}/outputs/product-analysis/product-analysis-{date}.md"

# --- DIRECTIVE ---
# ═══════════════════════════════════════════════════════════════
# ⚠️ MANDATORY EXECUTION - DO NOT SKIP
# ═══════════════════════════════════════════════════════════════
# You MUST execute BOTH steps below in order:
#   1. initialization → READ and EXECUTE workflow-init.md
#   2. execution → READ and EXECUTE workflow-execution.md
# STOP immediately and report error if any step fails.
# ═══════════════════════════════════════════════════════════════
directive:
  initialization: "./framework/components/workflow-init.md"
  execution: "./framework/components/workflow-execution.md"
