# GitHub Actions workflow for skill auditing
# Copy to .github/workflows/skill-audit.yml in your skill repo

name: Skill Audit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check required files
        run: |
          echo "Checking required files..."
          [ -f "SKILL.md" ] && echo "✓ SKILL.md exists" || (echo "✗ SKILL.md missing" && exit 1)
          [ -f "README.md" ] && echo "✓ README.md exists" || echo "⚠ README.md missing (recommended)"
          [ -f "LICENSE" ] || [ -f "LICENSE.md" ] && echo "✓ LICENSE exists" || echo "⚠ LICENSE missing"
      
      - name: Check for secrets
        run: |
          echo "Scanning for potential secrets..."
          if grep -rniE "(api[_-]?key|secret|password|token|bearer)\s*[=:]\s*['\"]?[a-zA-Z0-9]{16,}" . --include="*.md" 2>/dev/null | grep -v "example\|sample\|your[_-]"; then
            echo "⚠ Potential secrets found - please review"
            exit 1
          fi
          
          if grep -rniE "(sk-[a-zA-Z0-9]{20,}|ghp_[a-zA-Z0-9]{20,}|gho_[a-zA-Z0-9]{20,})" . --include="*.md" 2>/dev/null; then
            echo "✗ API key patterns found"
            exit 1
          fi
          echo "✓ No obvious secrets found"
      
      - name: Check for hardcoded paths
        run: |
          echo "Checking for hardcoded paths..."
          if grep -rniE "\/home\/[a-z]+" . --include="*.md" 2>/dev/null; then
            echo "✗ Hardcoded /home/ paths found"
            exit 1
          fi
          if grep -rniE "\/Users\/[a-zA-Z]+" . --include="*.md" 2>/dev/null; then
            echo "✗ Hardcoded /Users/ paths found"
            exit 1
          fi
          echo "✓ No hardcoded paths"
      
      - name: Check for TODOs
        run: |
          echo "Checking for TODOs..."
          TODO_COUNT=$(grep -rniE "(TODO|FIXME|XXX)" . --include="*.md" 2>/dev/null | wc -l || echo 0)
          if [ "$TODO_COUNT" -gt 0 ]; then
            echo "⚠ Found $TODO_COUNT TODO/FIXME items:"
            grep -rniE "(TODO|FIXME|XXX)" . --include="*.md" 2>/dev/null | head -5
          else
            echo "✓ No TODOs found"
          fi
      
      - name: Validate internal links
        run: |
          echo "Checking internal links..."
          ERRORS=0
          for file in $(find . -name "*.md" -type f); do
            links=$(grep -oE '\[.*\]\(\.?/?[^)]+\.md\)' "$file" 2>/dev/null | grep -oE '\(\.?/?[^)]+\.md\)' | tr -d '()' || true)
            for link in $links; do
              dir=$(dirname "$file")
              target="$dir/$link"
              if [ ! -f "$target" ]; then
                echo "✗ Broken link: $file → $link"
                ERRORS=$((ERRORS + 1))
              fi
            done
          done
          [ $ERRORS -eq 0 ] && echo "✓ All internal links valid" || exit 1
      
      - name: Check SKILL.md structure
        run: |
          echo "Checking SKILL.md structure..."
          if [ -f "SKILL.md" ]; then
            if grep -qi "when to use\|## when" SKILL.md; then
              echo "✓ SKILL.md has 'When to Use' section"
            else
              echo "⚠ SKILL.md missing 'When to Use' section"
            fi
          fi
      
      - name: Size analysis
        run: |
          echo "Analyzing size..."
          TOTAL_BYTES=$(find . -name "*.md" -type f -exec cat {} \; | wc -c)
          TOKENS_EST=$((TOTAL_BYTES / 4))
          echo "Total size: $TOTAL_BYTES bytes (~$TOKENS_EST tokens)"
          
          if [ $TOKENS_EST -gt 20000 ]; then
            echo "⚠ Large skill - may impact context significantly"
          elif [ $TOKENS_EST -gt 10000 ]; then
            echo "⚠ Moderate size - consider splitting"
          else
            echo "✓ Good size"
          fi
